import type { Metadata } from 'next';
import type { JSX } from 'react';

import { Geist, Geist_Mono as GeistMono } from 'next/font/google';

import { Providers } from '@/components/providers';
import '@/app/globals.css';

const geistSans = Geist({
  subsets: ['latin-ext'],
  variable: '--font-geist-sans',
});

const geistMono = GeistMono({
  subsets: ['latin-ext'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html className={`${geistSans.variable} ${geistMono.variable} dark:scheme-dark antialiased`} lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
