/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsPkgRouteImport } from './routes/docs/$pkg'
import { Route as DocsChar123pkgChar125DotmdRouteImport } from './routes/docs/{$pkg}[.]md'
import { Route as UiIndexRouteImport } from './routes/ui/index'
import { Route as UiAboutRouteImport } from './routes/ui/about'
import { Route as DocsPkgKindRouteImport } from './routes/docs/$pkg_/$kind'
import { Route as DocsPkgChar123kindChar125DotmdRouteImport } from './routes/docs/$pkg_/{$kind}[.]md'
import { Route as UiComponentsIndexRouteImport } from './routes/ui/components/index'
import { Route as UiComponentsSlugRouteImport } from './routes/ui/components/$slug'
import { Route as UiComponentsChar123slugChar125DotmdRouteImport } from './routes/ui/components/{$slug}[.]md'
import { Route as DocsPkgKindPageRouteImport } from './routes/docs/$pkg_/$kind_/$page'
import { Route as DocsPkgKindChar123pageChar125DotmdRouteImport } from './routes/docs/$pkg_/$kind_/{$page}[.]md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPkgRoute = DocsPkgRouteImport.update({
  id: '/docs/$pkg',
  path: '/docs/$pkg',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123pkgChar125DotmdRoute =
  DocsChar123pkgChar125DotmdRouteImport.update({
    id: '/docs/{$pkg}.md',
    path: '/docs/{$pkg}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const UiIndexRoute = UiIndexRouteImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiAboutRoute = UiAboutRouteImport.update({
  id: '/ui/about',
  path: '/ui/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPkgKindRoute = DocsPkgKindRouteImport.update({
  id: '/docs/$pkg_/$kind',
  path: '/docs/$pkg/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPkgChar123kindChar125DotmdRoute =
  DocsPkgChar123kindChar125DotmdRouteImport.update({
    id: '/docs/$pkg_/{$kind}.md',
    path: '/docs/$pkg/{$kind}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const UiComponentsIndexRoute = UiComponentsIndexRouteImport.update({
  id: '/ui/components/',
  path: '/ui/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const UiComponentsSlugRoute = UiComponentsSlugRouteImport.update({
  id: '/ui/components/$slug',
  path: '/ui/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UiComponentsChar123slugChar125DotmdRoute =
  UiComponentsChar123slugChar125DotmdRouteImport.update({
    id: '/ui/components/{$slug}.md',
    path: '/ui/components/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsPkgKindPageRoute = DocsPkgKindPageRouteImport.update({
  id: '/docs/$pkg_/$kind_/$page',
  path: '/docs/$pkg/$kind/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPkgKindChar123pageChar125DotmdRoute =
  DocsPkgKindChar123pageChar125DotmdRouteImport.update({
    id: '/docs/$pkg_/$kind_/{$page}.md',
    path: '/docs/$pkg/$kind/{$page}.md',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/docs/$pkg': typeof DocsPkgRoute
  '/docs/{$pkg}.md': typeof DocsChar123pkgChar125DotmdRoute
  '/ui/about': typeof UiAboutRoute
  '/docs/': typeof DocsIndexRoute
  '/ui/': typeof UiIndexRoute
  '/docs/$pkg/$kind': typeof DocsPkgKindRoute
  '/docs/$pkg/{$kind}.md': typeof DocsPkgChar123kindChar125DotmdRoute
  '/ui/components/$slug': typeof UiComponentsSlugRoute
  '/ui/components/{$slug}.md': typeof UiComponentsChar123slugChar125DotmdRoute
  '/ui/components/': typeof UiComponentsIndexRoute
  '/docs/$pkg/$kind/$page': typeof DocsPkgKindPageRoute
  '/docs/$pkg/$kind/{$page}.md': typeof DocsPkgKindChar123pageChar125DotmdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/docs/$pkg': typeof DocsPkgRoute
  '/docs/{$pkg}.md': typeof DocsChar123pkgChar125DotmdRoute
  '/ui/about': typeof UiAboutRoute
  '/docs': typeof DocsIndexRoute
  '/ui': typeof UiIndexRoute
  '/docs/$pkg/$kind': typeof DocsPkgKindRoute
  '/docs/$pkg/{$kind}.md': typeof DocsPkgChar123kindChar125DotmdRoute
  '/ui/components/$slug': typeof UiComponentsSlugRoute
  '/ui/components/{$slug}.md': typeof UiComponentsChar123slugChar125DotmdRoute
  '/ui/components': typeof UiComponentsIndexRoute
  '/docs/$pkg/$kind/$page': typeof DocsPkgKindPageRoute
  '/docs/$pkg/$kind/{$page}.md': typeof DocsPkgKindChar123pageChar125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/docs/$pkg': typeof DocsPkgRoute
  '/docs/{$pkg}.md': typeof DocsChar123pkgChar125DotmdRoute
  '/ui/about': typeof UiAboutRoute
  '/docs/': typeof DocsIndexRoute
  '/ui/': typeof UiIndexRoute
  '/docs/$pkg_/$kind': typeof DocsPkgKindRoute
  '/docs/$pkg_/{$kind}.md': typeof DocsPkgChar123kindChar125DotmdRoute
  '/ui/components/$slug': typeof UiComponentsSlugRoute
  '/ui/components/{$slug}.md': typeof UiComponentsChar123slugChar125DotmdRoute
  '/ui/components/': typeof UiComponentsIndexRoute
  '/docs/$pkg_/$kind_/$page': typeof DocsPkgKindPageRoute
  '/docs/$pkg_/$kind_/{$page}.md': typeof DocsPkgKindChar123pageChar125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/privacy'
    | '/docs/$pkg'
    | '/docs/{$pkg}.md'
    | '/ui/about'
    | '/docs/'
    | '/ui/'
    | '/docs/$pkg/$kind'
    | '/docs/$pkg/{$kind}.md'
    | '/ui/components/$slug'
    | '/ui/components/{$slug}.md'
    | '/ui/components/'
    | '/docs/$pkg/$kind/$page'
    | '/docs/$pkg/$kind/{$page}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/privacy'
    | '/docs/$pkg'
    | '/docs/{$pkg}.md'
    | '/ui/about'
    | '/docs'
    | '/ui'
    | '/docs/$pkg/$kind'
    | '/docs/$pkg/{$kind}.md'
    | '/ui/components/$slug'
    | '/ui/components/{$slug}.md'
    | '/ui/components'
    | '/docs/$pkg/$kind/$page'
    | '/docs/$pkg/$kind/{$page}.md'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/privacy'
    | '/docs/$pkg'
    | '/docs/{$pkg}.md'
    | '/ui/about'
    | '/docs/'
    | '/ui/'
    | '/docs/$pkg_/$kind'
    | '/docs/$pkg_/{$kind}.md'
    | '/ui/components/$slug'
    | '/ui/components/{$slug}.md'
    | '/ui/components/'
    | '/docs/$pkg_/$kind_/$page'
    | '/docs/$pkg_/$kind_/{$page}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  DocsPkgRoute: typeof DocsPkgRoute
  DocsChar123pkgChar125DotmdRoute: typeof DocsChar123pkgChar125DotmdRoute
  UiAboutRoute: typeof UiAboutRoute
  DocsIndexRoute: typeof DocsIndexRoute
  UiIndexRoute: typeof UiIndexRoute
  DocsPkgKindRoute: typeof DocsPkgKindRoute
  DocsPkgChar123kindChar125DotmdRoute: typeof DocsPkgChar123kindChar125DotmdRoute
  UiComponentsSlugRoute: typeof UiComponentsSlugRoute
  UiComponentsChar123slugChar125DotmdRoute: typeof UiComponentsChar123slugChar125DotmdRoute
  UiComponentsIndexRoute: typeof UiComponentsIndexRoute
  DocsPkgKindPageRoute: typeof DocsPkgKindPageRoute
  DocsPkgKindChar123pageChar125DotmdRoute: typeof DocsPkgKindChar123pageChar125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$pkg': {
      id: '/docs/$pkg'
      path: '/docs/$pkg'
      fullPath: '/docs/$pkg'
      preLoaderRoute: typeof DocsPkgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$pkg}.md': {
      id: '/docs/{$pkg}.md'
      path: '/docs/{$pkg}.md'
      fullPath: '/docs/{$pkg}.md'
      preLoaderRoute: typeof DocsChar123pkgChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/': {
      id: '/ui/'
      path: '/ui'
      fullPath: '/ui/'
      preLoaderRoute: typeof UiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/about': {
      id: '/ui/about'
      path: '/ui/about'
      fullPath: '/ui/about'
      preLoaderRoute: typeof UiAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$pkg_/$kind': {
      id: '/docs/$pkg_/$kind'
      path: '/docs/$pkg/$kind'
      fullPath: '/docs/$pkg/$kind'
      preLoaderRoute: typeof DocsPkgKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$pkg_/{$kind}.md': {
      id: '/docs/$pkg_/{$kind}.md'
      path: '/docs/$pkg/{$kind}.md'
      fullPath: '/docs/$pkg/{$kind}.md'
      preLoaderRoute: typeof DocsPkgChar123kindChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/components/': {
      id: '/ui/components/'
      path: '/ui/components'
      fullPath: '/ui/components/'
      preLoaderRoute: typeof UiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/components/$slug': {
      id: '/ui/components/$slug'
      path: '/ui/components/$slug'
      fullPath: '/ui/components/$slug'
      preLoaderRoute: typeof UiComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui/components/{$slug}.md': {
      id: '/ui/components/{$slug}.md'
      path: '/ui/components/{$slug}.md'
      fullPath: '/ui/components/{$slug}.md'
      preLoaderRoute: typeof UiComponentsChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$pkg_/$kind_/$page': {
      id: '/docs/$pkg_/$kind_/$page'
      path: '/docs/$pkg/$kind/$page'
      fullPath: '/docs/$pkg/$kind/$page'
      preLoaderRoute: typeof DocsPkgKindPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$pkg_/$kind_/{$page}.md': {
      id: '/docs/$pkg_/$kind_/{$page}.md'
      path: '/docs/$pkg/$kind/{$page}.md'
      fullPath: '/docs/$pkg/$kind/{$page}.md'
      preLoaderRoute: typeof DocsPkgKindChar123pageChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  DocsPkgRoute: DocsPkgRoute,
  DocsChar123pkgChar125DotmdRoute: DocsChar123pkgChar125DotmdRoute,
  UiAboutRoute: UiAboutRoute,
  DocsIndexRoute: DocsIndexRoute,
  UiIndexRoute: UiIndexRoute,
  DocsPkgKindRoute: DocsPkgKindRoute,
  DocsPkgChar123kindChar125DotmdRoute: DocsPkgChar123kindChar125DotmdRoute,
  UiComponentsSlugRoute: UiComponentsSlugRoute,
  UiComponentsChar123slugChar125DotmdRoute:
    UiComponentsChar123slugChar125DotmdRoute,
  UiComponentsIndexRoute: UiComponentsIndexRoute,
  DocsPkgKindPageRoute: DocsPkgKindPageRoute,
  DocsPkgKindChar123pageChar125DotmdRoute:
    DocsPkgKindChar123pageChar125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
