import { getDefaultClassNames } from '@/lib/helpers/get-default-class-names';

test('should return the default classnames', () => {
  expect(getDefaultClassNames()).toStrictEqual({
    button_next: 'rdp-button_next',
    button_previous: 'rdp-button_previous',
    caption_label: 'rdp-caption_label',
    chevron: 'rdp-chevron',
    day: 'rdp-day',
    day_button: 'rdp-day_button',
    disabled: 'rdp-disabled',
    dropdown: 'rdp-dropdown',
    dropdown_root: 'rdp-dropdown_root',
    dropdowns: 'rdp-dropdowns',
    focused: 'rdp-focused',
    footer: 'rdp-footer',
    hidden: 'rdp-hidden',
    month: 'rdp-month',
    month_caption: 'rdp-month_caption',
    month_grid: 'rdp-month_grid',
    months: 'rdp-months',
    months_dropdown: 'rdp-months_dropdown',
    nav: 'rdp-nav',
    outside: 'rdp-outside',
    range_end: 'rdp-range_end',
    range_middle: 'rdp-range_middle',
    range_start: 'rdp-range_start',
    root: 'rdp-root',
    selected: 'rdp-selected',
    today: 'rdp-today',
    week: 'rdp-week',
    week_number: 'rdp-week_number',
    week_number_header: 'rdp-week_number_header',
    weekday: 'rdp-weekday',
    weekdays: 'rdp-weekdays',
    weeks: 'rdp-weeks',
    years_dropdown: 'rdp-years_dropdown',
  });
});
