// Shared oxc config fragment imported by oxlint.config.ts and oxfmt.config.ts.
// Both tools already honor .gitignore on their real invocations (`oxlint .`, `oxfmt`
// over the cwd — verified), so every generated/build artifact (node_modules, dist,
// .turbo, coverage, .output, .nitro, .tanstack, …) is skipped without an entry here.
// Only list files that are committed (so .gitignore does NOT cover them) yet must be skipped.
export const ignorePatterns: Array<string> = [
  "**/pnpm-lock.yaml", // committed lockfile — oxfmt would otherwise reformat it as YAML
  "**/routeTree.gen.ts", // committed, but generated by TanStack Router
];
