import { Toaster } from "@codefast/ui/sonner";
import { cn } from "@codefast/ui/utils";
import type { Metadata } from "next";
import "@/styles/globals.css";
import React from "react";
import { Providers } from "@/components/providers";
import { inter } from "@/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en" className={cn(inter.variable, "dark")}>
      <body>
        <div vaul-drawer-wrapper="">
          <Providers>{children}</Providers>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
