import { inter } from '@/app/fonts';
import '@/app/globals.css';
import { Providers } from '@/components/providers';
import { type Metadata } from 'next';
import { type JSX, type ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>): JSX.Element {
  return (
    <html className={inter.variable} lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
