/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiRouteImport } from './routes/di'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as UiRouteImport } from './routes/ui'
import { Route as VariantsRouteImport } from './routes/variants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiRoute = DiRouteImport.update({
  id: '/di',
  path: '/di',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const UiRoute = UiRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/di': typeof DiRoute
  '/inspector': typeof InspectorRoute
  '/playground': typeof PlaygroundRoute
  '/ui': typeof UiRoute
  '/variants': typeof VariantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/di': typeof DiRoute
  '/inspector': typeof InspectorRoute
  '/playground': typeof PlaygroundRoute
  '/ui': typeof UiRoute
  '/variants': typeof VariantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/di': typeof DiRoute
  '/inspector': typeof InspectorRoute
  '/playground': typeof PlaygroundRoute
  '/ui': typeof UiRoute
  '/variants': typeof VariantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/di' | '/inspector' | '/playground' | '/ui' | '/variants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/di' | '/inspector' | '/playground' | '/ui' | '/variants'
  id:
    | '__root__'
    | '/'
    | '/di'
    | '/inspector'
    | '/playground'
    | '/ui'
    | '/variants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiRoute: typeof DiRoute
  InspectorRoute: typeof InspectorRoute
  PlaygroundRoute: typeof PlaygroundRoute
  UiRoute: typeof UiRoute
  VariantsRoute: typeof VariantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/di': {
      id: '/di'
      path: '/di'
      fullPath: '/di'
      preLoaderRoute: typeof DiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ui': {
      id: '/ui'
      path: '/ui'
      fullPath: '/ui'
      preLoaderRoute: typeof UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiRoute: DiRoute,
  InspectorRoute: InspectorRoute,
  PlaygroundRoute: PlaygroundRoute,
  UiRoute: UiRoute,
  VariantsRoute: VariantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
