import type { Registry } from '@/scripts/lib/schema';

export const blocks: Registry['items'] = [
  {
    name: 'sidebar-01',
    type: 'registry:block',
    description: 'A simple sidebar with navigation grouped by section.',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-02',
    description: 'A sidebar with collapsible sections.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-03',
    description: 'A sidebar with submenus.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-04',
    description: 'A floating sidebar with submenus.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-05',
    description: 'A sidebar with collapsible submenus.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-06',
    description: 'A sidebar with submenus as dropdowns.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-07',
    type: 'registry:block',
    description: 'A sidebar that collapses to icons.',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-08',
    description: 'An inset sidebar with secondary navigation.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-09',
    description: 'Collapsible nested sidebars.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-10',
    description: 'A sidebar in a popover.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-11',
    description: 'A sidebar with a collapsible file tree.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-12',
    description: 'A sidebar with a calendar.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-13',
    description: 'A sidebar in a dialog.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-14',
    description: 'A sidebar on the right.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-15',
    description: 'A left and right sidebar.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'sidebar-16',
    description: 'A sidebar with a sticky site header.',
    type: 'registry:block',
    categories: ['sidebar', 'dashboard'],
  },
  {
    name: 'login-01',
    description: 'A simple login form.',
    type: 'registry:block',
    categories: ['authentication', 'login'],
  },
  {
    name: 'login-02',
    description: 'A two column login page with a cover image.',
    type: 'registry:block',
    categories: ['authentication', 'login'],
  },
  {
    name: 'login-03',
    description: 'A login page with a muted background color.',
    type: 'registry:block',
    categories: ['authentication', 'login'],
  },
  {
    name: 'login-04',
    description: 'A login page with form and image.',
    type: 'registry:block',
    categories: ['authentication', 'login'],
  },
  {
    name: 'login-05',
    description: 'A simple email-only login page.',
    type: 'registry:block',
    categories: ['authentication', 'login'],
  },
  {
    name: 'products-01',
    description: 'A table of products',
    type: 'registry:block',
  },
];
