name: 'Setup Build Environment'
description: 'Sets up Node.js, pnpm, and project dependencies with caching for efficient CI/CD builds. Configures Turbo build caching and installs all required dependencies using pnpm.'
author: 'thevuong'

inputs:
  node-version:
    description: 'Node.js version to use'
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM Package Manager
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install Project Dependencies
      shell: bash
      run: pnpm install --prefer-offline

    - name: Setup Turbo
      uses: dtinth/setup-github-actions-caching-for-turbo@v1
      continue-on-error: true
      with:
        # Set the prefix for the cache keys.
        cache-prefix: turborepo_
