name: 'Setup Environment'
description: 'This GitHub Actions workflow sets up the necessary environment for the project. It installs pnpm, Node.js 20, and the project dependencies using pnpm, while leveraging caching mechanisms to improve build speeds and efficiency. Additionally, it configures Turbo for better build caching, addressing potential issues during the setup process to ensure a smooth CI/CD pipeline.'

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --prefer-offline

    - name: Setup Turbo
      uses: dtinth/setup-github-actions-caching-for-turbo@v1
      continue-on-error: true
      with:
        # Set the prefix for the cache keys.
        cache-prefix: turborepo_
