/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsChar123slugChar125DottxtRouteImport } from './routes/components/{$slug}[.]txt'
import { Route as ComponentsSlugRouteImport } from './routes/components/$slug'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChar123slugChar125DottxtRoute =
  ComponentsChar123slugChar125DottxtRouteImport.update({
    id: '/components/{$slug}.txt',
    path: '/components/{$slug}.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: '/components/$slug',
  path: '/components/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/{$slug}.txt': typeof ComponentsChar123slugChar125DottxtRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/{$slug}.txt': typeof ComponentsChar123slugChar125DottxtRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/components/$slug': typeof ComponentsSlugRoute
  '/components/{$slug}.txt': typeof ComponentsChar123slugChar125DottxtRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/llms.txt'
    | '/components/$slug'
    | '/components/{$slug}.txt'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/llms.txt'
    | '/components/$slug'
    | '/components/{$slug}.txt'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/llms.txt'
    | '/components/$slug'
    | '/components/{$slug}.txt'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRouteRoute: typeof AboutRouteRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ComponentsSlugRoute: typeof ComponentsSlugRoute
  ComponentsChar123slugChar125DottxtRoute: typeof ComponentsChar123slugChar125DottxtRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/{$slug}.txt': {
      id: '/components/{$slug}.txt'
      path: '/components/{$slug}.txt'
      fullPath: '/components/{$slug}.txt'
      preLoaderRoute: typeof ComponentsChar123slugChar125DottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/components/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRouteRoute: AboutRouteRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsChar123slugChar125DottxtRoute:
    ComponentsChar123slugChar125DottxtRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
