blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/codefastlabs/codefast/issues/new?template=feature_request.md
    about: Suggest an idea for this project
  - name: Bug Report
    url: https://github.com/codefastlabs/codefast/issues/new?template=bug_report.md
    about: Create a report to help us improve
  - name: Ask a Question
    url: https://github.com/codefastlabs/codefast/discussions/new?category=q-a
    about: Ask questions about the project
