/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SinkRouteRouteImport } from './routes/sink/route'
import { Route as SinkIndexRouteImport } from './routes/sink/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as SinkTanstackFormIndexRouteImport } from './routes/sink/tanstack-form/index'
import { Route as SinkStartFormIndexRouteImport } from './routes/sink/start-form/index'
import { Route as SinkReactHookFormIndexRouteImport } from './routes/sink/react-hook-form/index'
import { Route as SinkFormsIndexRouteImport } from './routes/sink/forms/index'
import { Route as SinkNameIndexRouteImport } from './routes/sink/$name/index'
import { Route as AppThemeIndexRouteImport } from './routes/_app/theme/index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SinkRouteRoute = SinkRouteRouteImport.update({
  id: '/sink',
  path: '/sink',
  getParentRoute: () => rootRouteImport,
} as any)
const SinkIndexRoute = SinkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SinkRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SinkTanstackFormIndexRoute = SinkTanstackFormIndexRouteImport.update({
  id: '/tanstack-form/',
  path: '/tanstack-form/',
  getParentRoute: () => SinkRouteRoute,
} as any)
const SinkStartFormIndexRoute = SinkStartFormIndexRouteImport.update({
  id: '/start-form/',
  path: '/start-form/',
  getParentRoute: () => SinkRouteRoute,
} as any)
const SinkReactHookFormIndexRoute = SinkReactHookFormIndexRouteImport.update({
  id: '/react-hook-form/',
  path: '/react-hook-form/',
  getParentRoute: () => SinkRouteRoute,
} as any)
const SinkFormsIndexRoute = SinkFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => SinkRouteRoute,
} as any)
const SinkNameIndexRoute = SinkNameIndexRouteImport.update({
  id: '/$name/',
  path: '/$name/',
  getParentRoute: () => SinkRouteRoute,
} as any)
const AppThemeIndexRoute = AppThemeIndexRouteImport.update({
  id: '/theme/',
  path: '/theme/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sink': typeof SinkRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/sink/': typeof SinkIndexRoute
  '/theme/': typeof AppThemeIndexRoute
  '/sink/$name/': typeof SinkNameIndexRoute
  '/sink/forms/': typeof SinkFormsIndexRoute
  '/sink/react-hook-form/': typeof SinkReactHookFormIndexRoute
  '/sink/start-form/': typeof SinkStartFormIndexRoute
  '/sink/tanstack-form/': typeof SinkTanstackFormIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/sink': typeof SinkIndexRoute
  '/theme': typeof AppThemeIndexRoute
  '/sink/$name': typeof SinkNameIndexRoute
  '/sink/forms': typeof SinkFormsIndexRoute
  '/sink/react-hook-form': typeof SinkReactHookFormIndexRoute
  '/sink/start-form': typeof SinkStartFormIndexRoute
  '/sink/tanstack-form': typeof SinkTanstackFormIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sink': typeof SinkRouteRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/sink/': typeof SinkIndexRoute
  '/_app/theme/': typeof AppThemeIndexRoute
  '/sink/$name/': typeof SinkNameIndexRoute
  '/sink/forms/': typeof SinkFormsIndexRoute
  '/sink/react-hook-form/': typeof SinkReactHookFormIndexRoute
  '/sink/start-form/': typeof SinkStartFormIndexRoute
  '/sink/tanstack-form/': typeof SinkTanstackFormIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sink'
    | '/'
    | '/sink/'
    | '/theme/'
    | '/sink/$name/'
    | '/sink/forms/'
    | '/sink/react-hook-form/'
    | '/sink/start-form/'
    | '/sink/tanstack-form/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sink'
    | '/theme'
    | '/sink/$name'
    | '/sink/forms'
    | '/sink/react-hook-form'
    | '/sink/start-form'
    | '/sink/tanstack-form'
  id:
    | '__root__'
    | '/sink'
    | '/_app'
    | '/_app/'
    | '/sink/'
    | '/_app/theme/'
    | '/sink/$name/'
    | '/sink/forms/'
    | '/sink/react-hook-form/'
    | '/sink/start-form/'
    | '/sink/tanstack-form/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SinkRouteRoute: typeof SinkRouteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sink': {
      id: '/sink'
      path: '/sink'
      fullPath: '/sink'
      preLoaderRoute: typeof SinkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sink/': {
      id: '/sink/'
      path: '/'
      fullPath: '/sink/'
      preLoaderRoute: typeof SinkIndexRouteImport
      parentRoute: typeof SinkRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sink/tanstack-form/': {
      id: '/sink/tanstack-form/'
      path: '/tanstack-form'
      fullPath: '/sink/tanstack-form/'
      preLoaderRoute: typeof SinkTanstackFormIndexRouteImport
      parentRoute: typeof SinkRouteRoute
    }
    '/sink/start-form/': {
      id: '/sink/start-form/'
      path: '/start-form'
      fullPath: '/sink/start-form/'
      preLoaderRoute: typeof SinkStartFormIndexRouteImport
      parentRoute: typeof SinkRouteRoute
    }
    '/sink/react-hook-form/': {
      id: '/sink/react-hook-form/'
      path: '/react-hook-form'
      fullPath: '/sink/react-hook-form/'
      preLoaderRoute: typeof SinkReactHookFormIndexRouteImport
      parentRoute: typeof SinkRouteRoute
    }
    '/sink/forms/': {
      id: '/sink/forms/'
      path: '/forms'
      fullPath: '/sink/forms/'
      preLoaderRoute: typeof SinkFormsIndexRouteImport
      parentRoute: typeof SinkRouteRoute
    }
    '/sink/$name/': {
      id: '/sink/$name/'
      path: '/$name'
      fullPath: '/sink/$name/'
      preLoaderRoute: typeof SinkNameIndexRouteImport
      parentRoute: typeof SinkRouteRoute
    }
    '/_app/theme/': {
      id: '/_app/theme/'
      path: '/theme'
      fullPath: '/theme/'
      preLoaderRoute: typeof AppThemeIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SinkRouteRouteChildren {
  SinkIndexRoute: typeof SinkIndexRoute
  SinkNameIndexRoute: typeof SinkNameIndexRoute
  SinkFormsIndexRoute: typeof SinkFormsIndexRoute
  SinkReactHookFormIndexRoute: typeof SinkReactHookFormIndexRoute
  SinkStartFormIndexRoute: typeof SinkStartFormIndexRoute
  SinkTanstackFormIndexRoute: typeof SinkTanstackFormIndexRoute
}

const SinkRouteRouteChildren: SinkRouteRouteChildren = {
  SinkIndexRoute: SinkIndexRoute,
  SinkNameIndexRoute: SinkNameIndexRoute,
  SinkFormsIndexRoute: SinkFormsIndexRoute,
  SinkReactHookFormIndexRoute: SinkReactHookFormIndexRoute,
  SinkStartFormIndexRoute: SinkStartFormIndexRoute,
  SinkTanstackFormIndexRoute: SinkTanstackFormIndexRoute,
}

const SinkRouteRouteWithChildren = SinkRouteRoute._addFileChildren(
  SinkRouteRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppThemeIndexRoute: typeof AppThemeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppThemeIndexRoute: AppThemeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SinkRouteRoute: SinkRouteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
