import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { cn } from "@codefast/tailwind-variants";
import { ActiveThemeProvider } from "@/components/active-theme";
import { Toaster } from "@codefast/ui/sonner";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(geistSans.variable, geistMono.variable, "antialiased")}>
        <ThemeProvider>
          <ActiveThemeProvider>
            {children}
            <Toaster position="top-center" />
          </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
