import '@/styles/globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { fontVariables } from '@/lib/fonts';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { ActiveThemeProvider } from '@/components/active-theme';
import { Toaster } from '@codefast/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fontVariables}>
        <ThemeProvider>
          <ActiveThemeProvider>
            {children}
            <Toaster position="top-center" />
          </ActiveThemeProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
