/**
 * Invariants that ARCHITECTURE.md states in prose and that nothing else checks: the single binding
 * shape, the direction of the layering, the curated export surface, and whether the document still
 * names things that exist. Each of these used to be held by a comment, which is the arrangement
 * that let them rot in the first place.
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { createBinding, DEFAULT_BINDING_SLOT } from "#/binding";
import { token } from "#/token";

const packageRoot = fileURLToPath(new URL("../../", import.meta.url));
const sourceRoot = join(packageRoot, "src");

function sourceFiles(directory: string = sourceRoot): Array<string> {
  return readdirSync(directory).flatMap((entry) => {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) {
      return sourceFiles(full);
    }
    return full.endsWith(".ts") ? [full] : [];
  });
}

describe("every binding shares one shape", () => {
  it("produces identical keys, in identical order, for every kind", () => {
    const target = token<unknown>("architecture-shape");
    const kinds = [
      { kind: "constant", value: 1 },
      { kind: "dynamic", factory: () => 1, scope: "transient" },
      { kind: "dynamic-async", factory: () => Promise.resolve(1), scope: "transient" },
      { kind: "resolved", factory: () => 1, deps: [], scope: "transient" },
      { kind: "resolved-async", factory: () => Promise.resolve(1), deps: [], scope: "transient" },
      { kind: "alias", target },
    ];

    const shapes = kinds.map((kind) =>
      Object.keys(createBinding(kind as never, target, DEFAULT_BINDING_SLOT, undefined)).join(","),
    );

    // One V8 hidden class for every binding in the process is what keeps the resolver's hot
    // property reads monomorphic; a kind that grows a field, or a binding built by an object
    // literal somewhere else, shows up here as a different key order.
    expect(new Set(shapes).size).toBe(1);
    expect(shapes[0]).toMatchInlineSnapshot(
      `"kind,id,inFlight,frame,instance,token,slot,predicate,scope,target,factory,deps,value,onActivation,onDeactivation"`,
    );
  });
});

describe("the layering points one way", () => {
  // model → resolution → {decorators, metadata} → {container, introspection}. A decorator needs the
  // resolution environment (accessor injection resolves at property-access time); the container
  // composes all of it. Same-layer imports are fine; only an upward value import is a violation.
  const LAYERS: Record<string, number> = {
    "": 0,
    resolution: 1,
    decorators: 2,
    metadata: 2,
    container: 3,
    introspection: 3,
  };

  function layerOf(file: string): number {
    const relative = file.slice(sourceRoot.length + 1);
    const directory = relative.includes("/") ? relative.split("/")[0]! : "";
    return LAYERS[directory] ?? 0;
  }

  it("has no value import from a lower layer to a higher one", () => {
    const violations: Array<string> = [];

    for (const file of sourceFiles()) {
      // The root barrel composes every layer on purpose; that is what a barrel is for.
      if (file === join(sourceRoot, "index.ts")) {
        continue;
      }
      const source = readFileSync(file, "utf8");
      for (const match of source.matchAll(/^import\s+(type\s+)?[^;]*?from\s+"#\/([^"]+)"/gm)) {
        const [, typeOnly, specifier] = match;
        // A type-only import erases at build time, so it couples nothing at runtime.
        if (typeOnly !== undefined) {
          continue;
        }
        const importedDirectory = specifier!.includes("/") ? specifier!.split("/")[0]! : "";
        if ((LAYERS[importedDirectory] ?? 0) > layerOf(file)) {
          violations.push(`${file.slice(sourceRoot.length + 1)} → #/${specifier!}`);
        }
      }
    }

    expect(violations).toEqual([]);
  });
});

describe("the published surface stays curated", () => {
  it("exports exactly the intended subpaths", () => {
    const manifest = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8")) as {
      exports: Record<string, unknown>;
    };

    // Generated by `codefast mirror` from codefast.config.js. Pinned here so a new module under
    // an internal directory cannot quietly become part of the public API.
    expect(Object.keys(manifest.exports).sort()).toEqual([
      ".",
      "./decorators/inject",
      "./decorators/injectable",
      "./decorators/lifecycle-decorators",
      "./dependency-graph",
      "./errors",
      "./graph-adapters/cytoscape",
      "./graph-adapters/dot",
      "./graph-adapters/reactflow",
      "./inspector",
      "./metadata/metadata-reader-token",
      "./module",
      "./package.json",
      "./token",
      "./types",
    ]);
  });
});

describe("ARCHITECTURE.md still describes this package", () => {
  const doc = readFileSync(join(packageRoot, "ARCHITECTURE.md"), "utf8");

  it("links only to source files that exist", () => {
    const missing = [...doc.matchAll(/\]\((src\/[^)]+\.ts)\)/g)]
      .map((match) => match[1]!)
      .filter((relative) => {
        try {
          statSync(join(packageRoot, relative));
          return false;
        } catch {
          return true;
        }
      });

    expect(missing).toEqual([]);
  });

  it("names only symbols that exist", () => {
    const source = sourceFiles()
      .map((file) => readFileSync(file, "utf8"))
      .join("\n");
    // Identifiers the document presents as this package's own — `SomeClass`, `someFunction()`.
    const named = new Set(
      [...doc.matchAll(/`([A-Z][A-Za-z]{4,})`/g), ...doc.matchAll(/`([a-z][A-Za-z]{4,})\(\)`/g)].map(
        (match) => match[1]!,
      ),
    );
    // Words the document uses about the ecosystem rather than about this source tree.
    const external = new Set(["ARCHITECTURE", "RESULTS", "CONTRIBUTING", "InversifyJS", "Dagger", "Turborepo"]);

    const missing = [...named].filter((name) => !external.has(name) && !new RegExp(`\\b${name}\\b`).test(source));

    expect(missing).toEqual([]);
  });
});
