/**
 * Invariants that ARCHITECTURE.md states in prose and that nothing else checks: the single binding
 * shape, the direction of the layering, the curated export surface, and whether the document still
 * names things that exist. Each of these used to be held by a comment, which is the arrangement
 * that let them rot in the first place.
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { createBinding, DEFAULT_BINDING_SLOT } from "#/core/binding";
import { token } from "#/core/token";

const packageRoot = fileURLToPath(new URL("../../", import.meta.url));
const sourceRoot = join(packageRoot, "src");

function sourceFiles(directory: string = sourceRoot): Array<string> {
  return readdirSync(directory).flatMap((entry) => {
    const full = join(directory, entry);
    if (statSync(full).isDirectory()) {
      return sourceFiles(full);
    }
    return full.endsWith(".ts") ? [full] : [];
  });
}

describe("every binding shares one shape", () => {
  it("produces identical keys, in identical order, for every kind", () => {
    const target = token<unknown>("architecture-shape");
    const kinds = [
      { kind: "constant", value: 1 },
      { kind: "dynamic", factory: () => 1, scope: "transient" },
      { kind: "dynamic-async", factory: () => Promise.resolve(1), scope: "transient" },
      { kind: "resolved", factory: () => 1, deps: [], scope: "transient" },
      { kind: "resolved-async", factory: () => Promise.resolve(1), deps: [], scope: "transient" },
      { kind: "alias", target },
    ];

    const shapes = kinds.map((kind) =>
      Object.keys(createBinding(kind as never, target, DEFAULT_BINDING_SLOT, undefined)).join(","),
    );

    // One V8 hidden class for every binding in the process is what keeps the resolver's hot
    // property reads monomorphic; a kind that grows a field, or a binding built by an object
    // literal somewhere else, shows up here as a different key order.
    expect(new Set(shapes).size).toBe(1);
    expect(shapes[0]).toMatchInlineSnapshot(
      `"kind,id,inFlight,frame,instance,token,slot,predicate,scope,target,factory,deps,value,onActivation,onDeactivation"`,
    );
  });
});

describe("the layering points one way", () => {
  // {core, errors, injection} → {lifecycle, ambient} → resolution → {decorators, metadata} →
  // {container, introspection}. A decorator needs the ambient container (accessor injection
  // resolves at property-access time); the container composes all of it. Same-layer imports are
  // fine; only an upward value import is a violation.
  const LAYERS: Record<string, number> = {
    "": 0,
    core: 0,
    errors: 0,
    injection: 0,
    ambient: 1,
    lifecycle: 1,
    resolution: 2,
    decorators: 3,
    metadata: 3,
    container: 4,
    introspection: 4,
  };

  function layerOf(file: string): number {
    const relative = file.slice(sourceRoot.length + 1);
    const directory = relative.includes("/") ? relative.split("/")[0]! : "";
    return LAYERS[directory] ?? 0;
  }

  it("has no value import from a lower layer to a higher one", () => {
    const violations: Array<string> = [];

    for (const file of sourceFiles()) {
      // The root barrel composes every layer on purpose; that is what a barrel is for.
      if (file === join(sourceRoot, "index.ts")) {
        continue;
      }
      const source = readFileSync(file, "utf8");
      for (const match of source.matchAll(/^import\s+(type\s+)?[^;]*?from\s+"#\/([^"]+)"/gm)) {
        const [, typeOnly, specifier] = match;
        // A type-only import erases at build time, so it couples nothing at runtime.
        if (typeOnly !== undefined) {
          continue;
        }
        const importedDirectory = specifier!.includes("/") ? specifier!.split("/")[0]! : "";
        if ((LAYERS[importedDirectory] ?? 0) > layerOf(file)) {
          violations.push(`${file.slice(sourceRoot.length + 1)} → #/${specifier!}`);
        }
      }
    }

    expect(violations).toEqual([]);
  });
});

describe("the published surface mirrors the source tree", () => {
  it("exports every module, with introspection at its flat specifiers", () => {
    const manifest = JSON.parse(readFileSync(join(packageRoot, "package.json"), "utf8")) as {
      exports: Record<string, unknown>;
    };

    // Generated by `codefast mirror` from codefast.config.js: every module is an entry point,
    // and `strip: "./introspection/"` keeps those specifiers where they originally shipped.
    // A missing entry means an exclusion crept back into the mirror config or `mirror` wasn't
    // rerun after adding a module.
    const expected = sourceFiles()
      .map((file) => file.slice(sourceRoot.length + 1).replace(/\.ts$/, ""))
      .map((module) => (module === "index" ? "." : `./${module.replace(/^introspection\//, "")}`));

    expect(Object.keys(manifest.exports).sort()).toEqual([...expected, "./package.json"].sort());
  });
});

describe("ARCHITECTURE.md still describes this package", () => {
  const doc = readFileSync(join(packageRoot, "ARCHITECTURE.md"), "utf8");

  it("links only to source files that exist", () => {
    const missing = [...doc.matchAll(/\]\((src\/[^)]+\.ts)\)/g)]
      .map((match) => match[1]!)
      .filter((relative) => {
        try {
          statSync(join(packageRoot, relative));
          return false;
        } catch {
          return true;
        }
      });

    expect(missing).toEqual([]);
  });

  it("names only test files that exist", () => {
    // The document pins a rule by naming the test that holds it, so a moved test file turns a
    // citation into a dead end. Backticked here rather than linked, which is why the link check
    // above does not see them.
    const missing = [...doc.matchAll(/`(tests\/[^`]+\.test\.ts)`/g)]
      .map((match) => match[1]!)
      .filter((relative) => {
        try {
          statSync(join(packageRoot, relative));
          return false;
        } catch {
          return true;
        }
      });

    expect(missing).toEqual([]);
  });

  it("names only symbols that exist", () => {
    const source = sourceFiles()
      .map((file) => readFileSync(file, "utf8"))
      .join("\n");
    // Identifiers the document presents as this package's own — `SomeClass`, `someFunction()`.
    const named = new Set(
      [...doc.matchAll(/`([A-Z][A-Za-z]{4,})`/g), ...doc.matchAll(/`([a-z][A-Za-z]{4,})\(\)`/g)].map(
        (match) => match[1]!,
      ),
    );
    // Words the document uses about the ecosystem rather than about this source tree.
    const external = new Set(["ARCHITECTURE", "RESULTS", "CONTRIBUTING", "InversifyJS", "Dagger", "Turborepo"]);

    const missing = [...named].filter((name) => !external.has(name) && !new RegExp(`\\b${name}\\b`).test(source));

    expect(missing).toEqual([]);
  });
});

describe("comments stay comments", () => {
  const COMMENT = /^\s*(?:\/\/|\*|\/\*)(.*)$/;
  // A number in a source comment cannot be re-verified where it sits and the method behind it is
  // not there either, so it goes stale silently. Numbers live with their method — ARCHITECTURE.md,
  // RESULTS.md, or the commit.
  const NUMBERS = /\b\d+(?:\.\d+)?\s*(?:×|x faster|%|ns\/op|µs|ms\b|KB|MB|bytes)\b/;
  // Code describes what is. Git carries what was.
  const HISTORY =
    /\b(?:used to|previously|an earlier (?:revision|draft|version)|the old \w+|before \w+ existed|no longer surfaces)\b/i;
  // A comment pointing at a document couples code to a heading no compiler checks: a section number
  // shifts the moment one is inserted, and a topic phrase outlives the section it named. State the
  // invariant here instead — if one line will not hold it, the name above it is not saying enough.
  const DOC_REFERENCE = /(?:\b\w+\.md\b|\bSPEC §|§\d)/;

  it.each([
    ["a benchmark number", NUMBERS],
    ["a narrated history", HISTORY],
    ["a pointer into a document", DOC_REFERENCE],
  ])("contains no %s", (_label, pattern) => {
    const offenders: Array<string> = [];

    for (const file of sourceFiles()) {
      const lines = readFileSync(file, "utf8").split("\n");
      for (const [index, line] of lines.entries()) {
        const body = COMMENT.exec(line)?.[1];
        if (body !== undefined && pattern.test(body)) {
          offenders.push(`${file.slice(sourceRoot.length + 1)}:${String(index + 1)} ${body.trim()}`);
        }
      }
    }

    expect(offenders).toEqual([]);
  });
});

describe("every failure this package raises is part of its taxonomy", () => {
  // The SPEC check below only sees `export class …Error`, so a bare `new Error(…)` was invisible to
  // it — and invisible to a consumer's `catch (error) { if (error instanceof DiError) … }`.
  it("throws only DiError subclasses", () => {
    const offenders: Array<string> = [];

    for (const file of sourceFiles()) {
      const lines = readFileSync(file, "utf8").split("\n");
      for (const [index, line] of lines.entries()) {
        if (/throw new (?:Error|TypeError|RangeError)\(/.test(line)) {
          offenders.push(`${file.slice(sourceRoot.length + 1)}:${String(index + 1)}`);
        }
      }
    }

    expect(offenders).toEqual([]);
  });

  it("exports every error class from the root barrel", () => {
    const declared = [
      ...readFileSync(join(sourceRoot, "errors", "errors.ts"), "utf8").matchAll(/export class ([A-Z][A-Za-z]*Error)/g),
    ].map((match) => match[1]!);
    const barrel = readFileSync(join(sourceRoot, "index.ts"), "utf8");

    const unexported = declared.filter((name) => !new RegExp(`\\b${name}\\b`).test(barrel));

    expect(unexported).toEqual([]);
  });
});

describe("SPEC.md keeps up with the API it specifies", () => {
  const spec = readFileSync(join(packageRoot, "SPEC.md"), "utf8");

  it("documents every error the package can throw", () => {
    const declared = [
      ...readFileSync(join(sourceRoot, "errors", "errors.ts"), "utf8").matchAll(/export class ([A-Z][A-Za-z]*Error)/g),
    ].map((match) => match[1]!);

    const undocumented = declared.filter((name) => !new RegExp(`\\b${name}\\b`).test(spec));

    expect(undocumented).toEqual([]);
  });

  it("documents every method on the Container interface", () => {
    const container = readFileSync(join(sourceRoot, "container", "container.ts"), "utf8");
    const members = [
      .../export interface Container \{([\s\S]*?)\n\}/
        .exec(container)![1]!
        .matchAll(/^ {2}([a-zA-Z][A-Za-z0-9]*)[<(]/gm),
    ].map((match) => match[1]!);

    const undocumented = [...new Set(members)].filter((name) => !new RegExp(`\\b${name}\\b`).test(spec));

    // Coverage only. Whether the prose still describes the behaviour correctly is a human job —
    // four semantic claims in this document were wrong before anyone checked.
    expect(undocumented).toEqual([]);
  });

  // A cross-reference used to be a bare section number, which goes stale silently the moment a
  // section is inserted — one such reference pointed at a §4.8 that had never existed.
  it("resolves every internal cross-reference", () => {
    const targets = new Set([...spec.matchAll(/<a id="([^"]+)"><\/a>/g)].map((match) => match[1]!));

    // The table of contents links headings by their rendered slug, so those count as targets too.
    for (const heading of spec.matchAll(/^#{1,3} (.+)$/gm)) {
      targets.add(
        heading[1]!
          .toLowerCase()
          .replaceAll(/[^\p{L}\p{N} -]/gu, "")
          .trim()
          .replaceAll(" ", "-"),
      );
    }

    const dangling = [...spec.matchAll(/]\(#([^)]+)\)/g)]
      .map((match) => match[1]!)
      .filter((target) => !targets.has(target));

    expect([...new Set(dangling)]).toEqual([]);
  });

  it("leaves no cross-reference as a bare section number", () => {
    // Links carry their own section number as label text, so strip them before looking. The
    // sub-number is optional: a whole-section reference rots the same way, and one pointing at
    // the wrong section survived here until the pattern stopped requiring a dot.
    const withoutLinks = spec.replaceAll(/\[[^\]]*]\([^)]*\)/g, "");
    const bare = [...withoutLinks.matchAll(/(?:section |§)\d+(?:\.\d+)?/gi)].map((match) => match[0]);

    expect([...new Set(bare)]).toEqual([]);
  });

  // The label carries the section number the reader sees; the anchor only keeps the jump working.
  // Renumber a section and the link still lands, silently labelled with the old number.
  it("labels every cross-reference with the section it lands on", () => {
    const lines = spec.split("\n");
    const sectionOfAnchor = new Map<string, string>();

    for (const [index, line] of lines.entries()) {
      const anchor = /<a id="([^"]+)"><\/a>/.exec(line);
      if (anchor === null) {
        continue;
      }
      // The anchor sits a blank line above its heading, never further.
      for (const candidate of lines.slice(index + 1, index + 4)) {
        const heading = /^#{2,3} (\d+(?:\.\d+)?)\.? /.exec(candidate);
        if (heading !== null) {
          sectionOfAnchor.set(anchor[1]!, heading[1]!);
          break;
        }
      }
    }

    const mislabelled: Array<string> = [];

    for (const link of spec.matchAll(/\[([^\]]*?)]\(#([^)]+)\)/g)) {
      const [, label, target] = link;
      const landsOn = sectionOfAnchor.get(target!);
      const claimed = /(?:section |§|xem )(\d+(?:\.\d+)?)/i.exec(label!);
      if (landsOn !== undefined && claimed !== null && claimed[1] !== landsOn) {
        mislabelled.push(`[${label!}](#${target!}) → section ${landsOn}`);
      }
    }

    expect([...new Set(mislabelled)]).toEqual([]);
  });

  // SPEC.md stops duplicating declarations by pointing at the file that holds them, which only
  // works while the pointer resolves — and no compiler reads prose.
  it("points only at source files that exist, naming only symbols they export", () => {
    const dangling: Array<string> = [];

    for (const pointer of spec.matchAll(/^> \*\*Hình dạng chính xác:\*\* (.+)$/gm)) {
      // One pointer may cite two files, separated by a semicolon: `a.ts` — `X`; `b.ts` — `Y`.
      for (const clause of pointer[1]!.split(";")) {
        const cited = [...clause.matchAll(/`([^`]+)`/g)].map((match) => match[1]!);
        const [path, ...symbols] = cited;
        if (path === undefined) {
          continue;
        }

        let source: string;
        try {
          source = readFileSync(join(packageRoot, path), "utf8");
        } catch {
          dangling.push(path);
          continue;
        }

        // Prose between the backticks ("bảy interface thành viên") carries no backticks, so only
        // real identifiers reach this filter.
        for (const symbol of symbols.filter((name) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(name))) {
          if (!new RegExp(`\\b${symbol}\\b`).test(source)) {
            dangling.push(`${path} — ${symbol}`);
          }
        }
      }
    }

    expect(dangling).toEqual([]);
  });
});
