import type { Metadata } from 'next';
import type { JSX } from 'react';

import { cn } from '@codefast/ui';
import { Geist, Geist_Mono as GeistMono } from 'next/font/google';

import '@/app/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html className={cn(geistSans.variable, geistMono.variable, 'antialiased')} lang="en">
      <body>{children}</body>
    </html>
  );
}
