import "@/app/globals.css";

import type { Metadata } from "next";
import type { JSX } from "react";

import { fontVariables } from "@/lib/fonts";
import { cn } from "@codefast/tailwind-variants";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={cn(fontVariables, "antialiased")}>{children}</body>
    </html>
  );
}
