import {
  type VegasAnimation,
  type VegasSettings,
  type VegasTransition,
} from '@/slideshow/_lib/types';

export const DEFAULT_TRANSITIONS: VegasTransition[] = [
  'fade',
  'fade2',
  'blur',
  'blur2',
  'flash',
  'flash2',
  'negative',
  'negative2',
  'burn',
  'burn2',
  'slideLeft',
  'slideLeft2',
  'slideRight',
  'slideRight2',
  'slideUp',
  'slideUp2',
  'slideDown',
  'slideDown2',
  'zoomIn',
  'zoomIn2',
  'zoomOut',
  'zoomOut2',
  'swirlLeft',
  'swirlLeft2',
  'swirlRight',
  'swirlRight2',
];

export const DEFAULT_ANIMATIONS: VegasAnimation[] = [
  'kenburns',
  'kenburnsLeft',
  'kenburnsRight',
  'kenburnsUp',
  'kenburnsUpLeft',
  'kenburnsUpRight',
  'kenburnsDown',
  'kenburnsDownLeft',
  'kenburnsDownRight',
];

export const DEFAULT_SETTINGS: VegasSettings = {
  firstTransition: null,
  firstTransitionDuration: 0,
  animation: 'random',
  color: '',
  slideIndex: 0,
  delay: 5000,
  loop: true,
  preload: false,
  preloadImage: false,
  preloadVideo: false,
  timer: true,
  overlay: false,
  autoplay: true,
  shuffle: false,
  cover: true,
  align: 'center',
  alignVertical: 'center',
  transition: 'fade',
  transitionDuration: 1000,
  transitionRegister: [],
  animationDuration: 'auto',
  animationRegister: [],
  slidesToKeep: 1,
  slides: [],
};
