name: Publish Packages

on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  NODE_VERSION: 20
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: true

jobs:
  publish:
    name: Publish to NPM
    # Only run when the PR is merged and the title contains "chore(release): version packages"
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Publish to NPM
        uses: changesets/action@v1
        with:
          publish: pnpm changeset:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
