name: "CI: Code Quality Assurance"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - canary

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: true

jobs:
  build:
    name: "Build Packages"
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup CI Environment"
        uses: ./.github/actions/setup-environment

      - name: "Build All Packages"
        run: pnpx turbo run build --filter="./packages/**"

  lint:
    name: "Run Linter"
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup CI Environment"
        uses: ./.github/actions/setup-environment

      - name: "Lint All Files"
        run: pnpx turbo run lint --filter="./packages/**"

  typecheck:
    name: "Perform Type-Checking"
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup CI Environment"
        uses: ./.github/actions/setup-environment

      - name: "Verify TypeScript Types"
        run: pnpx turbo run check-types --filter="./packages/**"

  test:
    name: "Run Tests with Coverage"
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup CI Environment"
        uses: ./.github/actions/setup-environment

      - name: "Execute Unit Tests"
        run: pnpx turbo run test:coverage:ci --filter="./packages/**"

      - name: "Upload Test Coverage Reports"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: codefastlabs/codefast
          fail_ci_if_error: false
