name: "CI: Security Checks"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - canary

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies-audit:
    name: "Audit Dependencies for Vulnerabilities"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup CI Environment"
        uses: ./.github/actions/setup-environment

      - name: "Run Dependency Audit (pnpm)"
        run: pnpm audit --prod

  code-scanning:
    name: "CodeQL Static Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Initialize CodeQL Scanner"
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript
          queries: security-and-quality

      - name: "Setup CI Environment"
        uses: ./.github/actions/setup-environment

      - name: "Build Project Packages"
        run: pnpx turbo run build --filter="./packages/**"

      - name: "Run CodeQL Analysis"
        uses: github/codeql-action/analyze@v3

  secrets-scanning:
    name: "Scan for Exposed Secrets"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Run TruffleHog Secrets Scanner"
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
