name: Create Version PR

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20
  SKIP_INSTALL_SIMPLE_GIT_HOOKS: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      ui_changed: ${{ steps.filter.outputs.ui }}
      test_required: ${{ steps.filter.outputs.test }}
      has_changeset: ${{ steps.filter.outputs.changeset }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check for Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ui:
              - 'packages/**/src/**/*.{js,jsx,ts,tsx,css,scss}'
              - 'apps/storybook-docs/**'
              - '**/tailwind.config.{js,ts}'
              - '**/*.stories.{js,jsx,ts,tsx}'
              - '**/styles/**'
            test:
              - 'packages/**/src/**/*.{js,jsx,ts,tsx}'
              - 'packages/**/__tests__/**'
              - 'packages/**/test/**'
              - '**/*.test.{js,jsx,ts,tsx}'
              - '**/*.spec.{js,jsx,ts,tsx}'
              - 'jest.config.{js,ts}'
              - 'vitest.config.{js,ts}'
              - '**/tests/**'
            changeset:
              - '.changeset/**/*.md'
              - '.changeset/config.json'

      - name: Log Filter Outputs
        run: |
          echo "UI Changed: ${{ steps.filter.outputs.ui }}"
          echo "Test Required: ${{ steps.filter.outputs.test }}"
          echo "Changeset Exists: ${{ steps.filter.outputs.changeset }}"
          echo "Message: ${{ github.event.head_commit.message }}"

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Lint
        run: pnpm lint

  test:
    name: Test
    needs: [setup, lint]
    if: |
      needs.setup.outputs.test_required == 'true' ||
      contains(github.event.head_commit.message, '[force-test]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Tests
        run: pnpm test

  chromatic:
    name: Visual Testing
    needs: [setup, lint]
    if: |
      needs.setup.outputs.ui_changed == 'true' &&
      (github.event_name == 'pull_request' || github.ref == 'refs/heads/main') &&
      !contains(github.event.head_commit.message, '[skip-visual]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/storybook-docs
          onlyChanged: true
          zip: true

  version:
    name: Create Version PR
    needs: [setup, lint, test]
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      needs.setup.outputs.has_changeset == 'true' &&
      !contains(github.event.head_commit.message, '[skip-release]') &&
      (needs.setup.outputs.test_required == 'false' || success())
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          title: 'chore(release): version packages'
          commit: 'chore(release): version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
